name: Deploy to Foam Village

# Trigger the workflow on push and
# pull request events on the production branch
on: workflow_dispatch

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to foamvillage
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FVHOST }}
          username: ${{ secrets.FVUSERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.FVSSHKEY }}
          script: "cd /home/foamvillageco/public_html && ./.scripts/deploy.sh"